// <auto-generated />
namespace Pins.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PinLog_ChangeIdType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PinLog_ChangeIdType));
        
        string IMigrationMetadata.Id
        {
            get { return "202106210045043_PinLog_ChangeIdType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
